//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 12:13:42 PM ART 
//


package org.devgateway.geocoder.iati.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}iati-identifier"/>
 *         &lt;element ref="{}reporting-org"/>
 *         &lt;element name="title" type="{}textRequiredType"/>
 *         &lt;element name="description" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}narrative" maxOccurs="unbounded"/>
 *                   &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;anyAttribute processContents='lax' namespace='##other'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}participating-org" maxOccurs="unbounded"/>
 *         &lt;element ref="{}other-identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}activity-status"/>
 *         &lt;element ref="{}activity-date" maxOccurs="unbounded"/>
 *         &lt;element ref="{}contact-info" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}activity-scope" minOccurs="0"/>
 *         &lt;element ref="{}recipient-country" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}recipient-region" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}location" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}sector" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}country-budget-items" minOccurs="0"/>
 *         &lt;element ref="{}humanitarian-scope" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}policy-marker" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}collaboration-type" minOccurs="0"/>
 *         &lt;element ref="{}default-flow-type" minOccurs="0"/>
 *         &lt;element ref="{}default-finance-type" minOccurs="0"/>
 *         &lt;element ref="{}default-aid-type" minOccurs="0"/>
 *         &lt;element ref="{}default-tied-status" minOccurs="0"/>
 *         &lt;element ref="{}budget" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}planned-disbursement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}capital-spend" minOccurs="0"/>
 *         &lt;element ref="{}transaction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}document-link" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}related-activity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}legacy-data" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}conditions" minOccurs="0"/>
 *         &lt;element ref="{}result" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}crs-add" minOccurs="0"/>
 *         &lt;element ref="{}fss" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="last-updated-datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *       &lt;attribute name="default-currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="humanitarian" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hierarchy" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="linked-data-uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iatiIdentifier",
    "reportingOrg",
    "title",
    "description",
    "participatingOrg",
    "otherIdentifier",
    "activityStatus",
    "activityDate",
    "contactInfo",
    "activityScope",
    "recipientCountry",
    "recipientRegion",
    "location",
    "sector",
    "countryBudgetItems",
    "humanitarianScope",
    "policyMarker",
    "collaborationType",
    "defaultFlowType",
    "defaultFinanceType",
    "defaultAidType",
    "defaultTiedStatus",
    "budget",
    "plannedDisbursement",
    "capitalSpend",
    "transaction",
    "documentLink",
    "relatedActivity",
    "legacyData",
    "conditions",
    "result",
    "crsAdd",
    "fss",
    "any"
})
@XmlRootElement(name = "iati-activity")
public class IatiActivity {

    @XmlElement(name = "iati-identifier", required = true)
    protected IatiIdentifier iatiIdentifier;
    @XmlElement(name = "reporting-org", required = true)
    protected ReportingOrg reportingOrg;
    @XmlElement(required = true)
    protected TextRequiredType title;
    @XmlElement(required = true)
    protected List<IatiActivity.Description> description;
    @XmlElement(name = "participating-org", required = true)
    protected List<ParticipatingOrg> participatingOrg;
    @XmlElement(name = "other-identifier")
    protected List<OtherIdentifier> otherIdentifier;
    @XmlElement(name = "activity-status", required = true)
    protected ActivityStatus activityStatus;
    @XmlElement(name = "activity-date", required = true)
    protected List<ActivityDate> activityDate;
    @XmlElement(name = "contact-info")
    protected List<ContactInfo> contactInfo;
    @XmlElement(name = "activity-scope")
    protected ActivityScope activityScope;
    @XmlElement(name = "recipient-country")
    protected List<RecipientCountry> recipientCountry;
    @XmlElement(name = "recipient-region")
    protected List<RecipientRegion> recipientRegion;
    protected List<Location> location;
    protected List<Sector> sector;
    @XmlElement(name = "country-budget-items")
    protected CountryBudgetItems countryBudgetItems;
    @XmlElement(name = "humanitarian-scope")
    protected List<HumanitarianScope> humanitarianScope;
    @XmlElement(name = "policy-marker")
    protected List<PolicyMarker> policyMarker;
    @XmlElement(name = "collaboration-type")
    protected CollaborationType collaborationType;
    @XmlElement(name = "default-flow-type")
    protected DefaultFlowType defaultFlowType;
    @XmlElement(name = "default-finance-type")
    protected DefaultFinanceType defaultFinanceType;
    @XmlElement(name = "default-aid-type")
    protected DefaultAidType defaultAidType;
    @XmlElement(name = "default-tied-status")
    protected DefaultTiedStatus defaultTiedStatus;
    protected List<Budget> budget;
    @XmlElement(name = "planned-disbursement")
    protected List<PlannedDisbursement> plannedDisbursement;
    @XmlElement(name = "capital-spend")
    protected CapitalSpend capitalSpend;
    protected List<Transaction> transaction;
    @XmlElement(name = "document-link")
    protected List<DocumentLink> documentLink;
    @XmlElement(name = "related-activity")
    protected List<RelatedActivity> relatedActivity;
    @XmlElement(name = "legacy-data")
    protected List<LegacyData> legacyData;
    protected Conditions conditions;
    protected List<Result> result;
    @XmlElement(name = "crs-add")
    protected CrsAdd crsAdd;
    protected Fss fss;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "last-updated-datetime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdatedDatetime;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "default-currency")
    protected String defaultCurrency;
    @XmlAttribute(name = "humanitarian")
    protected Boolean humanitarian;
    @XmlAttribute(name = "hierarchy")
    protected Integer hierarchy;
    @XmlAttribute(name = "linked-data-uri")
    @XmlSchemaType(name = "anyURI")
    protected String linkedDataUri;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the iatiIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link IatiIdentifier }
     *     
     */
    public IatiIdentifier getIatiIdentifier() {
        return iatiIdentifier;
    }

    /**
     * Sets the value of the iatiIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IatiIdentifier }
     *     
     */
    public void setIatiIdentifier(IatiIdentifier value) {
        this.iatiIdentifier = value;
    }

    /**
     * Gets the value of the reportingOrg property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingOrg }
     *     
     */
    public ReportingOrg getReportingOrg() {
        return reportingOrg;
    }

    /**
     * Sets the value of the reportingOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingOrg }
     *     
     */
    public void setReportingOrg(ReportingOrg value) {
        this.reportingOrg = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link TextRequiredType }
     *     
     */
    public TextRequiredType getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextRequiredType }
     *     
     */
    public void setTitle(TextRequiredType value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IatiActivity.Description }
     * 
     * 
     */
    public List<IatiActivity.Description> getDescription() {
        if (description == null) {
            description = new ArrayList<IatiActivity.Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the participatingOrg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the participatingOrg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticipatingOrg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParticipatingOrg }
     * 
     * 
     */
    public List<ParticipatingOrg> getParticipatingOrg() {
        if (participatingOrg == null) {
            participatingOrg = new ArrayList<ParticipatingOrg>();
        }
        return this.participatingOrg;
    }

    /**
     * Gets the value of the otherIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherIdentifier }
     * 
     * 
     */
    public List<OtherIdentifier> getOtherIdentifier() {
        if (otherIdentifier == null) {
            otherIdentifier = new ArrayList<OtherIdentifier>();
        }
        return this.otherIdentifier;
    }

    /**
     * Gets the value of the activityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityStatus }
     *     
     */
    public ActivityStatus getActivityStatus() {
        return activityStatus;
    }

    /**
     * Sets the value of the activityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityStatus }
     *     
     */
    public void setActivityStatus(ActivityStatus value) {
        this.activityStatus = value;
    }

    /**
     * Gets the value of the activityDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activityDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivityDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivityDate }
     * 
     * 
     */
    public List<ActivityDate> getActivityDate() {
        if (activityDate == null) {
            activityDate = new ArrayList<ActivityDate>();
        }
        return this.activityDate;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactInfo }
     * 
     * 
     */
    public List<ContactInfo> getContactInfo() {
        if (contactInfo == null) {
            contactInfo = new ArrayList<ContactInfo>();
        }
        return this.contactInfo;
    }

    /**
     * Gets the value of the activityScope property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityScope }
     *     
     */
    public ActivityScope getActivityScope() {
        return activityScope;
    }

    /**
     * Sets the value of the activityScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityScope }
     *     
     */
    public void setActivityScope(ActivityScope value) {
        this.activityScope = value;
    }

    /**
     * Gets the value of the recipientCountry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipientCountry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecipientCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecipientCountry }
     * 
     * 
     */
    public List<RecipientCountry> getRecipientCountry() {
        if (recipientCountry == null) {
            recipientCountry = new ArrayList<RecipientCountry>();
        }
        return this.recipientCountry;
    }

    /**
     * Gets the value of the recipientRegion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipientRegion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecipientRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecipientRegion }
     * 
     * 
     */
    public List<RecipientRegion> getRecipientRegion() {
        if (recipientRegion == null) {
            recipientRegion = new ArrayList<RecipientRegion>();
        }
        return this.recipientRegion;
    }

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Location }
     * 
     * 
     */
    public List<Location> getLocation() {
        if (location == null) {
            location = new ArrayList<Location>();
        }
        return this.location;
    }

    /**
     * Gets the value of the sector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sector }
     * 
     * 
     */
    public List<Sector> getSector() {
        if (sector == null) {
            sector = new ArrayList<Sector>();
        }
        return this.sector;
    }

    /**
     * Gets the value of the countryBudgetItems property.
     * 
     * @return
     *     possible object is
     *     {@link CountryBudgetItems }
     *     
     */
    public CountryBudgetItems getCountryBudgetItems() {
        return countryBudgetItems;
    }

    /**
     * Sets the value of the countryBudgetItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryBudgetItems }
     *     
     */
    public void setCountryBudgetItems(CountryBudgetItems value) {
        this.countryBudgetItems = value;
    }

    /**
     * Gets the value of the humanitarianScope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the humanitarianScope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHumanitarianScope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HumanitarianScope }
     * 
     * 
     */
    public List<HumanitarianScope> getHumanitarianScope() {
        if (humanitarianScope == null) {
            humanitarianScope = new ArrayList<HumanitarianScope>();
        }
        return this.humanitarianScope;
    }

    /**
     * Gets the value of the policyMarker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policyMarker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicyMarker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolicyMarker }
     * 
     * 
     */
    public List<PolicyMarker> getPolicyMarker() {
        if (policyMarker == null) {
            policyMarker = new ArrayList<PolicyMarker>();
        }
        return this.policyMarker;
    }

    /**
     * Gets the value of the collaborationType property.
     * 
     * @return
     *     possible object is
     *     {@link CollaborationType }
     *     
     */
    public CollaborationType getCollaborationType() {
        return collaborationType;
    }

    /**
     * Sets the value of the collaborationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollaborationType }
     *     
     */
    public void setCollaborationType(CollaborationType value) {
        this.collaborationType = value;
    }

    /**
     * Gets the value of the defaultFlowType property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultFlowType }
     *     
     */
    public DefaultFlowType getDefaultFlowType() {
        return defaultFlowType;
    }

    /**
     * Sets the value of the defaultFlowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultFlowType }
     *     
     */
    public void setDefaultFlowType(DefaultFlowType value) {
        this.defaultFlowType = value;
    }

    /**
     * Gets the value of the defaultFinanceType property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultFinanceType }
     *     
     */
    public DefaultFinanceType getDefaultFinanceType() {
        return defaultFinanceType;
    }

    /**
     * Sets the value of the defaultFinanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultFinanceType }
     *     
     */
    public void setDefaultFinanceType(DefaultFinanceType value) {
        this.defaultFinanceType = value;
    }

    /**
     * Gets the value of the defaultAidType property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultAidType }
     *     
     */
    public DefaultAidType getDefaultAidType() {
        return defaultAidType;
    }

    /**
     * Sets the value of the defaultAidType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultAidType }
     *     
     */
    public void setDefaultAidType(DefaultAidType value) {
        this.defaultAidType = value;
    }

    /**
     * Gets the value of the defaultTiedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultTiedStatus }
     *     
     */
    public DefaultTiedStatus getDefaultTiedStatus() {
        return defaultTiedStatus;
    }

    /**
     * Sets the value of the defaultTiedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultTiedStatus }
     *     
     */
    public void setDefaultTiedStatus(DefaultTiedStatus value) {
        this.defaultTiedStatus = value;
    }

    /**
     * Gets the value of the budget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the budget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBudget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Budget }
     * 
     * 
     */
    public List<Budget> getBudget() {
        if (budget == null) {
            budget = new ArrayList<Budget>();
        }
        return this.budget;
    }

    /**
     * Gets the value of the plannedDisbursement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedDisbursement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedDisbursement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlannedDisbursement }
     * 
     * 
     */
    public List<PlannedDisbursement> getPlannedDisbursement() {
        if (plannedDisbursement == null) {
            plannedDisbursement = new ArrayList<PlannedDisbursement>();
        }
        return this.plannedDisbursement;
    }

    /**
     * Gets the value of the capitalSpend property.
     * 
     * @return
     *     possible object is
     *     {@link CapitalSpend }
     *     
     */
    public CapitalSpend getCapitalSpend() {
        return capitalSpend;
    }

    /**
     * Sets the value of the capitalSpend property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapitalSpend }
     *     
     */
    public void setCapitalSpend(CapitalSpend value) {
        this.capitalSpend = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transaction }
     * 
     * 
     */
    public List<Transaction> getTransaction() {
        if (transaction == null) {
            transaction = new ArrayList<Transaction>();
        }
        return this.transaction;
    }

    /**
     * Gets the value of the documentLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentLink }
     * 
     * 
     */
    public List<DocumentLink> getDocumentLink() {
        if (documentLink == null) {
            documentLink = new ArrayList<DocumentLink>();
        }
        return this.documentLink;
    }

    /**
     * Gets the value of the relatedActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedActivity }
     * 
     * 
     */
    public List<RelatedActivity> getRelatedActivity() {
        if (relatedActivity == null) {
            relatedActivity = new ArrayList<RelatedActivity>();
        }
        return this.relatedActivity;
    }

    /**
     * Gets the value of the legacyData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legacyData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegacyData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LegacyData }
     * 
     * 
     */
    public List<LegacyData> getLegacyData() {
        if (legacyData == null) {
            legacyData = new ArrayList<LegacyData>();
        }
        return this.legacyData;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setConditions(Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Result }
     * 
     * 
     */
    public List<Result> getResult() {
        if (result == null) {
            result = new ArrayList<Result>();
        }
        return this.result;
    }

    /**
     * Gets the value of the crsAdd property.
     * 
     * @return
     *     possible object is
     *     {@link CrsAdd }
     *     
     */
    public CrsAdd getCrsAdd() {
        return crsAdd;
    }

    /**
     * Sets the value of the crsAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrsAdd }
     *     
     */
    public void setCrsAdd(CrsAdd value) {
        this.crsAdd = value;
    }

    /**
     * Gets the value of the fss property.
     * 
     * @return
     *     possible object is
     *     {@link Fss }
     *     
     */
    public Fss getFss() {
        return fss;
    }

    /**
     * Sets the value of the fss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fss }
     *     
     */
    public void setFss(Fss value) {
        this.fss = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the lastUpdatedDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdatedDatetime() {
        return lastUpdatedDatetime;
    }

    /**
     * Sets the value of the lastUpdatedDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdatedDatetime(XMLGregorianCalendar value) {
        this.lastUpdatedDatetime = value;
    }

    /**
     * 
     *             ISO 639-1 code specifying the default language used in
     *             narrative elements throughout the activity. If this is not
     *             declared then the xml:lang attribute MUST be specified for
     *             each narrative element.
     *           
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the defaultCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCurrency() {
        return defaultCurrency;
    }

    /**
     * Sets the value of the defaultCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCurrency(String value) {
        this.defaultCurrency = value;
    }

    /**
     * Gets the value of the humanitarian property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHumanitarian() {
        return humanitarian;
    }

    /**
     * Sets the value of the humanitarian property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHumanitarian(Boolean value) {
        this.humanitarian = value;
    }

    /**
     * Gets the value of the hierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHierarchy() {
        return hierarchy;
    }

    /**
     * Sets the value of the hierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHierarchy(Integer value) {
        this.hierarchy = value;
    }

    /**
     * Gets the value of the linkedDataUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedDataUri() {
        return linkedDataUri;
    }

    /**
     * Sets the value of the linkedDataUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedDataUri(String value) {
        this.linkedDataUri = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}narrative" maxOccurs="unbounded"/>
     *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;anyAttribute processContents='lax' namespace='##other'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "narrative",
        "any"
    })
    public static class Description {

        @XmlElement(required = true)
        protected List<Narrative> narrative;
        @XmlAnyElement(lax = true)
        protected List<Object> any;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the narrative property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the narrative property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNarrative().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Narrative }
         * 
         * 
         */
        public List<Narrative> getNarrative() {
            if (narrative == null) {
                narrative = new ArrayList<Narrative>();
            }
            return this.narrative;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * {@link Object }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

}
