//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 12:13:42 PM ART 
//


package org.devgateway.geocoder.iati.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Comment_QNAME = new QName("", "comment");
    private final static QName _Title_QNAME = new QName("", "title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CrsAdd }
     * 
     */
    public CrsAdd createCrsAdd() {
        return new CrsAdd();
    }

    /**
     * Create an instance of {@link Fss }
     * 
     */
    public Fss createFss() {
        return new Fss();
    }

    /**
     * Create an instance of {@link OtherIdentifier }
     * 
     */
    public OtherIdentifier createOtherIdentifier() {
        return new OtherIdentifier();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link DocumentLink }
     * 
     */
    public DocumentLink createDocumentLink() {
        return new DocumentLink();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link Budget }
     * 
     */
    public Budget createBudget() {
        return new Budget();
    }

    /**
     * Create an instance of {@link PlannedDisbursement }
     * 
     */
    public PlannedDisbursement createPlannedDisbursement() {
        return new PlannedDisbursement();
    }

    /**
     * Create an instance of {@link IatiActivity }
     * 
     */
    public IatiActivity createIatiActivity() {
        return new IatiActivity();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link CountryBudgetItems }
     * 
     */
    public CountryBudgetItems createCountryBudgetItems() {
        return new CountryBudgetItems();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link Result.Indicator }
     * 
     */
    public Result.Indicator createResultIndicator() {
        return new Result.Indicator();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period }
     * 
     */
    public Result.Indicator.Period createResultIndicatorPeriod() {
        return new Result.Indicator.Period();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period.Actual }
     * 
     */
    public Result.Indicator.Period.Actual createResultIndicatorPeriodActual() {
        return new Result.Indicator.Period.Actual();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period.Target }
     * 
     */
    public Result.Indicator.Period.Target createResultIndicatorPeriodTarget() {
        return new Result.Indicator.Period.Target();
    }

    /**
     * Create an instance of {@link CrsAdd.LoanTerms }
     * 
     */
    public CrsAdd.LoanTerms createCrsAddLoanTerms() {
        return new CrsAdd.LoanTerms();
    }

    /**
     * Create an instance of {@link ActivityScope }
     * 
     */
    public ActivityScope createActivityScope() {
        return new ActivityScope();
    }

    /**
     * Create an instance of {@link DefaultTiedStatus }
     * 
     */
    public DefaultTiedStatus createDefaultTiedStatus() {
        return new DefaultTiedStatus();
    }

    /**
     * Create an instance of {@link CrsAdd.OtherFlags }
     * 
     */
    public CrsAdd.OtherFlags createCrsAddOtherFlags() {
        return new CrsAdd.OtherFlags();
    }

    /**
     * Create an instance of {@link CrsAdd.LoanStatus }
     * 
     */
    public CrsAdd.LoanStatus createCrsAddLoanStatus() {
        return new CrsAdd.LoanStatus();
    }

    /**
     * Create an instance of {@link Fss.Forecast }
     * 
     */
    public Fss.Forecast createFssForecast() {
        return new Fss.Forecast();
    }

    /**
     * Create an instance of {@link RecipientCountry }
     * 
     */
    public RecipientCountry createRecipientCountry() {
        return new RecipientCountry();
    }

    /**
     * Create an instance of {@link Narrative }
     * 
     */
    public Narrative createNarrative() {
        return new Narrative();
    }

    /**
     * Create an instance of {@link OtherIdentifier.OwnerOrg }
     * 
     */
    public OtherIdentifier.OwnerOrg createOtherIdentifierOwnerOrg() {
        return new OtherIdentifier.OwnerOrg();
    }

    /**
     * Create an instance of {@link CapitalSpend }
     * 
     */
    public CapitalSpend createCapitalSpend() {
        return new CapitalSpend();
    }

    /**
     * Create an instance of {@link RelatedActivity }
     * 
     */
    public RelatedActivity createRelatedActivity() {
        return new RelatedActivity();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link TextRequiredType }
     * 
     */
    public TextRequiredType createTextRequiredType() {
        return new TextRequiredType();
    }

    /**
     * Create an instance of {@link DefaultFinanceType }
     * 
     */
    public DefaultFinanceType createDefaultFinanceType() {
        return new DefaultFinanceType();
    }

    /**
     * Create an instance of {@link RecipientRegion }
     * 
     */
    public RecipientRegion createRecipientRegion() {
        return new RecipientRegion();
    }

    /**
     * Create an instance of {@link DocumentLink.Category }
     * 
     */
    public DocumentLink.Category createDocumentLinkCategory() {
        return new DocumentLink.Category();
    }

    /**
     * Create an instance of {@link DocumentLink.Language }
     * 
     */
    public DocumentLink.Language createDocumentLinkLanguage() {
        return new DocumentLink.Language();
    }

    /**
     * Create an instance of {@link DocumentLink.DocumentDate }
     * 
     */
    public DocumentLink.DocumentDate createDocumentLinkDocumentDate() {
        return new DocumentLink.DocumentDate();
    }

    /**
     * Create an instance of {@link LegacyData }
     * 
     */
    public LegacyData createLegacyData() {
        return new LegacyData();
    }

    /**
     * Create an instance of {@link ActivityStatus }
     * 
     */
    public ActivityStatus createActivityStatus() {
        return new ActivityStatus();
    }

    /**
     * Create an instance of {@link IatiIdentifier }
     * 
     */
    public IatiIdentifier createIatiIdentifier() {
        return new IatiIdentifier();
    }

    /**
     * Create an instance of {@link ActivityDate }
     * 
     */
    public ActivityDate createActivityDate() {
        return new ActivityDate();
    }

    /**
     * Create an instance of {@link HumanitarianScope }
     * 
     */
    public HumanitarianScope createHumanitarianScope() {
        return new HumanitarianScope();
    }

    /**
     * Create an instance of {@link Sector }
     * 
     */
    public Sector createSector() {
        return new Sector();
    }

    /**
     * Create an instance of {@link ContactInfo.Telephone }
     * 
     */
    public ContactInfo.Telephone createContactInfoTelephone() {
        return new ContactInfo.Telephone();
    }

    /**
     * Create an instance of {@link ContactInfo.Email }
     * 
     */
    public ContactInfo.Email createContactInfoEmail() {
        return new ContactInfo.Email();
    }

    /**
     * Create an instance of {@link ContactInfo.Website }
     * 
     */
    public ContactInfo.Website createContactInfoWebsite() {
        return new ContactInfo.Website();
    }

    /**
     * Create an instance of {@link Budget.PeriodStart }
     * 
     */
    public Budget.PeriodStart createBudgetPeriodStart() {
        return new Budget.PeriodStart();
    }

    /**
     * Create an instance of {@link Budget.PeriodEnd }
     * 
     */
    public Budget.PeriodEnd createBudgetPeriodEnd() {
        return new Budget.PeriodEnd();
    }

    /**
     * Create an instance of {@link CurrencyType }
     * 
     */
    public CurrencyType createCurrencyType() {
        return new CurrencyType();
    }

    /**
     * Create an instance of {@link PlannedDisbursement.PeriodStart }
     * 
     */
    public PlannedDisbursement.PeriodStart createPlannedDisbursementPeriodStart() {
        return new PlannedDisbursement.PeriodStart();
    }

    /**
     * Create an instance of {@link PlannedDisbursement.PeriodEnd }
     * 
     */
    public PlannedDisbursement.PeriodEnd createPlannedDisbursementPeriodEnd() {
        return new PlannedDisbursement.PeriodEnd();
    }

    /**
     * Create an instance of {@link PlannedDisbursement.ProviderOrg }
     * 
     */
    public PlannedDisbursement.ProviderOrg createPlannedDisbursementProviderOrg() {
        return new PlannedDisbursement.ProviderOrg();
    }

    /**
     * Create an instance of {@link PlannedDisbursement.ReceiverOrg }
     * 
     */
    public PlannedDisbursement.ReceiverOrg createPlannedDisbursementReceiverOrg() {
        return new PlannedDisbursement.ReceiverOrg();
    }

    /**
     * Create an instance of {@link CollaborationType }
     * 
     */
    public CollaborationType createCollaborationType() {
        return new CollaborationType();
    }

    /**
     * Create an instance of {@link DefaultAidType }
     * 
     */
    public DefaultAidType createDefaultAidType() {
        return new DefaultAidType();
    }

    /**
     * Create an instance of {@link PolicyMarker }
     * 
     */
    public PolicyMarker createPolicyMarker() {
        return new PolicyMarker();
    }

    /**
     * Create an instance of {@link ReportingOrg }
     * 
     */
    public ReportingOrg createReportingOrg() {
        return new ReportingOrg();
    }

    /**
     * Create an instance of {@link IatiActivity.Description }
     * 
     */
    public IatiActivity.Description createIatiActivityDescription() {
        return new IatiActivity.Description();
    }

    /**
     * Create an instance of {@link ParticipatingOrg }
     * 
     */
    public ParticipatingOrg createParticipatingOrg() {
        return new ParticipatingOrg();
    }

    /**
     * Create an instance of {@link Location.LocationReach }
     * 
     */
    public Location.LocationReach createLocationLocationReach() {
        return new Location.LocationReach();
    }

    /**
     * Create an instance of {@link Location.LocationId }
     * 
     */
    public Location.LocationId createLocationLocationId() {
        return new Location.LocationId();
    }

    /**
     * Create an instance of {@link Location.Administrative }
     * 
     */
    public Location.Administrative createLocationAdministrative() {
        return new Location.Administrative();
    }

    /**
     * Create an instance of {@link Location.Point }
     * 
     */
    public Location.Point createLocationPoint() {
        return new Location.Point();
    }

    /**
     * Create an instance of {@link Location.Exactness }
     * 
     */
    public Location.Exactness createLocationExactness() {
        return new Location.Exactness();
    }

    /**
     * Create an instance of {@link Location.LocationClass }
     * 
     */
    public Location.LocationClass createLocationLocationClass() {
        return new Location.LocationClass();
    }

    /**
     * Create an instance of {@link Location.FeatureDesignation }
     * 
     */
    public Location.FeatureDesignation createLocationFeatureDesignation() {
        return new Location.FeatureDesignation();
    }

    /**
     * Create an instance of {@link CountryBudgetItems.BudgetItem }
     * 
     */
    public CountryBudgetItems.BudgetItem createCountryBudgetItemsBudgetItem() {
        return new CountryBudgetItems.BudgetItem();
    }

    /**
     * Create an instance of {@link DefaultFlowType }
     * 
     */
    public DefaultFlowType createDefaultFlowType() {
        return new DefaultFlowType();
    }

    /**
     * Create an instance of {@link Transaction.TransactionType }
     * 
     */
    public Transaction.TransactionType createTransactionTransactionType() {
        return new Transaction.TransactionType();
    }

    /**
     * Create an instance of {@link Transaction.TransactionDate }
     * 
     */
    public Transaction.TransactionDate createTransactionTransactionDate() {
        return new Transaction.TransactionDate();
    }

    /**
     * Create an instance of {@link Transaction.ProviderOrg }
     * 
     */
    public Transaction.ProviderOrg createTransactionProviderOrg() {
        return new Transaction.ProviderOrg();
    }

    /**
     * Create an instance of {@link Transaction.ReceiverOrg }
     * 
     */
    public Transaction.ReceiverOrg createTransactionReceiverOrg() {
        return new Transaction.ReceiverOrg();
    }

    /**
     * Create an instance of {@link Transaction.DisbursementChannel }
     * 
     */
    public Transaction.DisbursementChannel createTransactionDisbursementChannel() {
        return new Transaction.DisbursementChannel();
    }

    /**
     * Create an instance of {@link Transaction.Sector }
     * 
     */
    public Transaction.Sector createTransactionSector() {
        return new Transaction.Sector();
    }

    /**
     * Create an instance of {@link Transaction.RecipientCountry }
     * 
     */
    public Transaction.RecipientCountry createTransactionRecipientCountry() {
        return new Transaction.RecipientCountry();
    }

    /**
     * Create an instance of {@link Transaction.RecipientRegion }
     * 
     */
    public Transaction.RecipientRegion createTransactionRecipientRegion() {
        return new Transaction.RecipientRegion();
    }

    /**
     * Create an instance of {@link Transaction.FlowType }
     * 
     */
    public Transaction.FlowType createTransactionFlowType() {
        return new Transaction.FlowType();
    }

    /**
     * Create an instance of {@link Transaction.FinanceType }
     * 
     */
    public Transaction.FinanceType createTransactionFinanceType() {
        return new Transaction.FinanceType();
    }

    /**
     * Create an instance of {@link Transaction.AidType }
     * 
     */
    public Transaction.AidType createTransactionAidType() {
        return new Transaction.AidType();
    }

    /**
     * Create an instance of {@link Transaction.TiedStatus }
     * 
     */
    public Transaction.TiedStatus createTransactionTiedStatus() {
        return new Transaction.TiedStatus();
    }

    /**
     * Create an instance of {@link Conditions.Condition }
     * 
     */
    public Conditions.Condition createConditionsCondition() {
        return new Conditions.Condition();
    }

    /**
     * Create an instance of {@link IatiActivities }
     * 
     */
    public IatiActivities createIatiActivities() {
        return new IatiActivities();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link Result.Indicator.Reference }
     * 
     */
    public Result.Indicator.Reference createResultIndicatorReference() {
        return new Result.Indicator.Reference();
    }

    /**
     * Create an instance of {@link Result.Indicator.Baseline }
     * 
     */
    public Result.Indicator.Baseline createResultIndicatorBaseline() {
        return new Result.Indicator.Baseline();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period.PeriodStart }
     * 
     */
    public Result.Indicator.Period.PeriodStart createResultIndicatorPeriodPeriodStart() {
        return new Result.Indicator.Period.PeriodStart();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period.PeriodEnd }
     * 
     */
    public Result.Indicator.Period.PeriodEnd createResultIndicatorPeriodPeriodEnd() {
        return new Result.Indicator.Period.PeriodEnd();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period.Actual.Location }
     * 
     */
    public Result.Indicator.Period.Actual.Location createResultIndicatorPeriodActualLocation() {
        return new Result.Indicator.Period.Actual.Location();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period.Actual.Dimension }
     * 
     */
    public Result.Indicator.Period.Actual.Dimension createResultIndicatorPeriodActualDimension() {
        return new Result.Indicator.Period.Actual.Dimension();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period.Target.Location }
     * 
     */
    public Result.Indicator.Period.Target.Location createResultIndicatorPeriodTargetLocation() {
        return new Result.Indicator.Period.Target.Location();
    }

    /**
     * Create an instance of {@link Result.Indicator.Period.Target.Dimension }
     * 
     */
    public Result.Indicator.Period.Target.Dimension createResultIndicatorPeriodTargetDimension() {
        return new Result.Indicator.Period.Target.Dimension();
    }

    /**
     * Create an instance of {@link CrsAdd.LoanTerms.RepaymentType }
     * 
     */
    public CrsAdd.LoanTerms.RepaymentType createCrsAddLoanTermsRepaymentType() {
        return new CrsAdd.LoanTerms.RepaymentType();
    }

    /**
     * Create an instance of {@link CrsAdd.LoanTerms.RepaymentPlan }
     * 
     */
    public CrsAdd.LoanTerms.RepaymentPlan createCrsAddLoanTermsRepaymentPlan() {
        return new CrsAdd.LoanTerms.RepaymentPlan();
    }

    /**
     * Create an instance of {@link CrsAdd.LoanTerms.CommitmentDate }
     * 
     */
    public CrsAdd.LoanTerms.CommitmentDate createCrsAddLoanTermsCommitmentDate() {
        return new CrsAdd.LoanTerms.CommitmentDate();
    }

    /**
     * Create an instance of {@link CrsAdd.LoanTerms.RepaymentFirstDate }
     * 
     */
    public CrsAdd.LoanTerms.RepaymentFirstDate createCrsAddLoanTermsRepaymentFirstDate() {
        return new CrsAdd.LoanTerms.RepaymentFirstDate();
    }

    /**
     * Create an instance of {@link CrsAdd.LoanTerms.RepaymentFinalDate }
     * 
     */
    public CrsAdd.LoanTerms.RepaymentFinalDate createCrsAddLoanTermsRepaymentFinalDate() {
        return new CrsAdd.LoanTerms.RepaymentFinalDate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextRequiredType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comment")
    public JAXBElement<TextRequiredType> createComment(TextRequiredType value) {
        return new JAXBElement<TextRequiredType>(_Comment_QNAME, TextRequiredType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextRequiredType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<TextRequiredType> createTitle(TextRequiredType value) {
        return new JAXBElement<TextRequiredType>(_Title_QNAME, TextRequiredType.class, null, value);
    }

}
