package org.devgateway.geocoder.repositories;

import org.devgateway.geocoder.domain.Administrative;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 06/11/2017
*/
@Repository
public interface AdminLevelRepository extends JpaRepository<Administrative, Long> {

}
