package org.devgateway.geocoder.repositories;

import org.devgateway.geocoder.domain.Country;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Spring Data Generator on 06/11/2017
 */
@Repository
@Transactional
public interface CountryRepository extends JpaRepository<Country, Long> {
    Country findOneByIso2(String code);
}
