package org.devgateway.geocoder.repositories;

import org.devgateway.geocoder.domain.IatiCodes;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Spring Data Generator on 06/11/2017
 */
@Repository
@Transactional
public interface IatiCodesRepository<T extends IatiCodes> extends JpaRepository<T, Long> {
    public T findOneByCode(String code);

    public T findOneByNameIgnoreCase(String name);
}
